# Generated by Django 5.1.4 on 2024-12-31 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
