# Generated by Django 5.1.4 on 2024-12-31 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0002_examplemodel_delete_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplemodel',
            name='email',
            field=models.EmailField(default='default@gmail.com', max_length=254),
        ),
    ]
