# Generated by Django 5.1.4 on 2024-12-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0003_examplemodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplemodel',
            name='furigana',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
