# Generated by Django 5.1.4 on 2024-12-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0004_examplemodel_furigana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplemodel',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
