# Generated by Django 5.1.4 on 2024-12-31 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0005_alter_examplemodel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examplemodel',
            old_name='furigana',
            new_name='お名前',
        ),
        migrations.RenameField(
            model_name='examplemodel',
            old_name='name',
            new_name='フリガナ',
        ),
        migrations.RenameField(
            model_name='examplemodel',
            old_name='email',
            new_name='メールアドレス',
        ),
    ]
