# Generated by Django 5.1.4 on 2024-12-31 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0006_rename_furigana_examplemodel_お名前_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplemodel',
            name='電話番号',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
