# Generated by Django 5.1.4 on 2025-01-01 13:26

import ao.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0009_examplemodel_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplemodel',
            name='check_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examplemodel',
            name='check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examplemodel',
            name='email',
            field=models.EmailField(blank=True, help_text='gmail,yahoo,icloudのみ有効', max_length=254, null=True, validators=[ao.models.validate_email]),
        ),
        migrations.AlterField(
            model_name='examplemodel',
            name='people',
            field=models.CharField(blank=True, choices=[('1', '1人'), ('2', '2人'), ('3', '3人'), ('4', '4人'), ('5', '5人'), ('6', '6人')], max_length=3, null=True),
        ),
    ]
