# Generated by Django 5.1.4 on 2025-01-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0011_alter_examplemodel_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplemodel',
            name='check_in_date',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='examplemodel',
            name='check_out_date',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
