# Generated by Django 5.1.4 on 2025-01-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0012_alter_examplemodel_check_in_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplemodel',
            name='check_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examplemodel',
            name='check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
