# Generated by Django 5.1.4 on 2025-01-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0014_alter_examplemodel_check_in_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='examplemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
